targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          include:
            - lib/utils/router.dart

      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/apis/model/*

      freezed:
        generate_for:
          include:
            - lib/apis/model/*
            - lib/model/dto/*
            - lib/model/*
            - lib/state/app_state.dart
