targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          exclude:
            - lib
          include:
            - lib/apis/model/*

      freezed:
        enabled: true
        generate_for:
          exclude:
            - lib
          include:
            - lib/apis/model/*
            - lib/model/dto/*
            - lib/model/*
            - lib/state/app_state.dart
