name: pokedex_flutter_async_redux
description: "Flutter App for Pokedex with Async Redux"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^25.4.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  dio: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.8.0
  device_preview_screenshot: ^1.0.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  go_router_builder: ^4.1.0

dependency_overrides:
  build: ^4.0.1

flutter:
  uses-material-design: true
