targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/apis/model/*

      freezed:
        generate_for:
          include:
            - lib/cubit/app_state.dart
            - lib/apis/model/*
            - lib/model/*
            - lib/feature/pokemon_info/cubit/*
