import 'package:flutter/material.dart';

const pokemonCardPadding = EdgeInsets.all(8.0);
const pokemonNamePadding = EdgeInsets.symmetric(vertical: 8.0);
const pokemonCardSize = 80.0;
const colorModifier = 0.1;
const pokemonTypeNamePadding = EdgeInsets.symmetric(vertical: 4.0, horizontal: 12.0);
const pokemonTypeNameMargin = EdgeInsets.only(bottom: 4.0, right: 8.0);
const typeNameRadius = 20.0;
const pokemonListPagePadding = EdgeInsets.symmetric(horizontal: 12.0);
const pokemonGridDelegate = SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent: 250, childAspectRatio: 3 / 2);
const pokemonListPageFooterHeight = 100.0;
const progressIndicatorFooterPadding = EdgeInsets.all(12.0);
const debouncerDelayInMilliseconds = 300;
const idNumberPadWidth = 3;
const infoPageHeaderPadding = EdgeInsets.symmetric(vertical: 8.0, horizontal: 16.0);
const infoPageImageSize = 200.0;
const infoPageModalPadding = EdgeInsets.symmetric(horizontal: 4.0);
const infoPageModalRadius = BorderRadius.vertical(top: Radius.circular(20.0));
const aboutTabPadding = EdgeInsets.all(16.0);
const flavorTextPadding = EdgeInsets.only(top: 8.0, bottom: 16.0);
